### ISSUE TITLE
nomad.get_job_submission is missing

### ISSUE THREAD

**Issue by thr27** [gbolo/hashicorp-ansible#1]
Hi,

I tried to use this plugin in ansible and I found a bug.

In ansible\plugins\modules\nomad_job.py line 105 you use nomad.get_job_submission, but this is missing in ansible\plugins\module_utils\nomad.py

...
```
  # if nomad_diff is not available we can try to fallback to a manual diff
        elif plan.get("Diff") is not None and existing_job is not None:
            submission = nomad.get_job_submission(
                job_id,
                existing_job.get("Version", 1),
            )
            if submission is not None:
                result["diff"] = dict(
                    before=submission.get("Source"),
                    after=module.params.get("hcl_spec"),
                )
```
...

Maybe you missed to checkin and push ?

I added

...
`URL_JOB_SUBMISSION = "{url}/v1/job/{id}/submission?namespace={namespace}&version={version}"`
...

And 
...
```
    def get_job_submission(self, id, version):
        return self.api_request(
            url=URL_JOB_SUBMISSION.format(url=self.url, id=id, namespace=quote_plus(self.namespace), version=version),
            method="GET",
            body=None,
            json_response=True,
        )

```...
Into ansible\plugins\module_utils\nomad.py to fix it

**Comment by gbolo** [comment]
Hi @thr27 ,

Thanks for catching this. You are correct, I missed a commit. I will double check if I missed anything else as well. I donated this code to a previous employer and seems like I added some code/fixes to that repo without porting it back here. I will PR this soon. Thanks again
